# Generated by Django 5.0.6 on 2024-07-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorinfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=1000)),
                ('doctor_image', models.ImageField(upload_to='')),
                ('specialist', models.CharField(max_length=1000)),
            ],
        ),
    ]
