# Generated by Django 5.0.6 on 2024-07-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctorinfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfor',
            name='doctor_image',
            field=models.ImageField(upload_to='doctor/'),
        ),
    ]
