# Generated by Django 5.0.6 on 2024-07-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_doctorinfor_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('p_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('contact', models.DecimalField(decimal_places=2, max_digits=10)),
                ('problem', models.CharField(max_length=100)),
            ],
        ),
    ]
